
import os, urllib.parse
from datetime import datetime, timedelta
from functools import wraps
from io import BytesIO

from flask import Flask, render_template, request, redirect, url_for, session, send_file
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import create_engine, text
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "troque-esta-chave")

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///oficina_ademar_local.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

ADMIN_USER = os.environ.get("ADMIN_USER", "admin")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "123456")

CORRECOES = {
    "MECANICA":"MECÂNICA","GERAL":"GERAL","REVISAO":"REVISÃO","SUSPENSAO":"SUSPENSÃO",
    "OLEO":"ÓLEO","CAMBIO":"CÂMBIO","INJECAO":"INJEÇÃO","DIRECAO":"DIREÇÃO",
    "ELETRICA":"ELÉTRICA","CABECOTE":"CABEÇOTE","MAO":"MÃO","PECAS":"PEÇAS",
    "ORCAMENTO":"ORÇAMENTO","VEICULO":"VEÍCULO","SERVICO":"SERVIÇO","SERVICOS":"SERVIÇOS",
    "DEBITO":"DÉBITO","CREDITO":"CRÉDITO","DESCRICAO":"DESCRIÇÃO","OBSERVACAO":"OBSERVAÇÃO",
    "OBSERVACOES":"OBSERVAÇÕES","ALINHAMENTO":"ALINHAMENTO","BALANCEAMENTO":"BALANCEAMENTO"
}

def normalizar(s):
    if s is None:
        return ""
    s = str(s).upper().strip()
    return " ".join(CORRECOES.get(p, p) for p in s.split())

def money(v):
    try:
        return float(str(v or "0").replace(".", "").replace(",", "."))
    except Exception:
        return 0.0

def brl(v):
    return f"R$ {float(v or 0):,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

@app.context_processor
def inject_helpers():
    return dict(brl=brl)

def init_db():
    with engine.begin() as con:
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS usuarios(
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            usuario VARCHAR(120) UNIQUE NOT NULL,
            senha_hash VARCHAR(255) NOT NULL
        );
        """))
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS clientes(
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            nome VARCHAR(180) NOT NULL,
            telefone VARCHAR(60),
            endereco VARCHAR(255),
            criado_em VARCHAR(20)
        );
        """))
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS veiculos(
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            cliente_id INTEGER,
            modelo VARCHAR(160),
            placa VARCHAR(30),
            ano VARCHAR(20),
            cor VARCHAR(60)
        );
        """))
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS orcamentos(
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            cliente_id INTEGER,
            veiculo_id INTEGER,
            data VARCHAR(20),
            status VARCHAR(40),
            descricao TEXT,
            pecas_desc TEXT,
            pecas_valor FLOAT,
            mao_obra_desc TEXT,
            mao_obra_valor FLOAT,
            desconto FLOAT,
            acrescimo FLOAT,
            total FLOAT,
            pagamento VARCHAR(40),
            parcelas INTEGER,
            valor_parcela FLOAT,
            primeira_parcela VARCHAR(20),
            observacoes TEXT
        );
        """))
        con.execute(text("""
        CREATE TABLE IF NOT EXISTS financeiro(
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            data VARCHAR(20),
            tipo VARCHAR(30),
            descricao TEXT,
            valor FLOAT,
            forma VARCHAR(40),
            orcamento_id INTEGER,
            parcela_num INTEGER,
            parcelas_total INTEGER,
            status VARCHAR(40)
        );
        """))
        row = con.execute(text("SELECT id FROM usuarios WHERE usuario=:u"), {"u": ADMIN_USER}).fetchone()
        if not row:
            con.execute(text("INSERT INTO usuarios(usuario,senha_hash) VALUES(:u,:s)"),
                        {"u": ADMIN_USER, "s": generate_password_hash(ADMIN_PASSWORD)})

init_db()

def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if not session.get("logado"):
            return redirect(url_for("login"))
        return f(*args, **kwargs)
    return wrapper

def fetchall(sql, params=None):
    with engine.begin() as con:
        return con.execute(text(sql), params or {}).mappings().all()

def fetchone(sql, params=None):
    with engine.begin() as con:
        return con.execute(text(sql), params or {}).mappings().fetchone()

def execute(sql, params=None):
    with engine.begin() as con:
        return con.execute(text(sql), params or {})

@app.route("/login", methods=["GET","POST"])
def login():
    erro = None
    if request.method == "POST":
        usuario = request.form.get("usuario","").strip()
        senha = request.form.get("senha","")
        user = fetchone("SELECT * FROM usuarios WHERE usuario=:u", {"u": usuario})
        if user and check_password_hash(user["senha_hash"], senha):
            session["logado"] = True
            session["usuario"] = usuario
            return redirect(url_for("index"))
        erro = "USUÁRIO OU SENHA INVÁLIDOS"
    return render_template("login.html", erro=erro)

@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))

@app.route("/")
@login_required
def index():
    clientes = fetchall("SELECT * FROM clientes ORDER BY id DESC LIMIT 5")
    orcs = fetchall("""SELECT o.*, c.nome cliente, v.modelo carro, v.placa placa
                       FROM orcamentos o
                       LEFT JOIN clientes c ON c.id=o.cliente_id
                       LEFT JOIN veiculos v ON v.id=o.veiculo_id
                       ORDER BY o.id DESC LIMIT 8""")
    ym = datetime.now().strftime("%Y-%m")
    total_mes = fetchone("""SELECT COALESCE(SUM(valor),0) total FROM financeiro
                            WHERE tipo='ENTRADA' AND substr(data,1,7)=:ym""", {"ym": ym})["total"]
    pendente = fetchone("""SELECT COALESCE(SUM(valor),0) total FROM financeiro
                           WHERE tipo='ENTRADA' AND status='PENDENTE'""")["total"]
    return render_template("index.html", clientes=clientes, orcs=orcs, total_mes=total_mes, pendente=pendente)

@app.route("/clientes", methods=["GET","POST"])
@login_required
def clientes():
    if request.method == "POST":
        execute("""INSERT INTO clientes(nome, telefone, endereco, criado_em)
                   VALUES(:nome,:telefone,:endereco,:criado)""",
                {"nome": normalizar(request.form["nome"]), "telefone": request.form.get("telefone",""),
                 "endereco": normalizar(request.form.get("endereco","")),
                 "criado": datetime.now().strftime("%Y-%m-%d")})
        return redirect(url_for("clientes"))
    lista = fetchall("SELECT * FROM clientes ORDER BY nome")
    return render_template("clientes.html", clientes=lista)

@app.route("/clientes/excluir/<int:id>")
@login_required
def excluir_cliente(id):
    execute("DELETE FROM clientes WHERE id=:id", {"id": id})
    return redirect(url_for("clientes"))

@app.route("/veiculos", methods=["GET","POST"])
@login_required
def veiculos():
    if request.method == "POST":
        execute("""INSERT INTO veiculos(cliente_id,modelo,placa,ano,cor)
                   VALUES(:cliente_id,:modelo,:placa,:ano,:cor)""",
                {"cliente_id": request.form["cliente_id"], "modelo": normalizar(request.form["modelo"]),
                 "placa": normalizar(request.form.get("placa","")).replace(" ",""),
                 "ano": normalizar(request.form.get("ano","")), "cor": normalizar(request.form.get("cor",""))})
        return redirect(url_for("veiculos"))
    clientes = fetchall("SELECT * FROM clientes ORDER BY nome")
    lista = fetchall("""SELECT v.*, c.nome cliente FROM veiculos v
                        LEFT JOIN clientes c ON c.id=v.cliente_id ORDER BY v.id DESC""")
    return render_template("veiculos.html", veiculos=lista, clientes=clientes)

@app.route("/veiculos/excluir/<int:id>")
@login_required
def excluir_veiculo(id):
    execute("DELETE FROM veiculos WHERE id=:id", {"id": id})
    return redirect(url_for("veiculos"))

def recalcular_parcelas(orc_id):
    execute("DELETE FROM financeiro WHERE orcamento_id=:id", {"id": orc_id})
    o = fetchone("SELECT * FROM orcamentos WHERE id=:id", {"id": orc_id})
    if not o:
        return
    parcelas = max(1, int(o["parcelas"] or 1))
    valor_parcela = float(o["valor_parcela"] or o["total"] or 0)
    try:
        data_base = datetime.strptime(o["primeira_parcela"] or o["data"], "%Y-%m-%d")
    except Exception:
        data_base = datetime.now()
    for i in range(parcelas):
        venc = data_base + timedelta(days=30*i)
        execute("""INSERT INTO financeiro(data,tipo,descricao,valor,forma,orcamento_id,parcela_num,parcelas_total,status)
                   VALUES(:data,'ENTRADA',:descricao,:valor,:forma,:orc,:num,:total,'PENDENTE')""",
                {"data": venc.strftime("%Y-%m-%d"), "descricao": f"ORÇAMENTO #{orc_id} - PARCELA {i+1}/{parcelas}",
                 "valor": valor_parcela, "forma": o["pagamento"], "orc": orc_id, "num": i+1, "total": parcelas})

@app.route("/orcamentos", methods=["GET","POST"])
@app.route("/orcamentos/editar/<int:edit_id>", methods=["GET","POST"])
@login_required
def orcamentos(edit_id=None):
    if request.method == "POST":
        pecas = money(request.form.get("pecas_valor"))
        mao = money(request.form.get("mao_obra_valor"))
        desconto = money(request.form.get("desconto"))
        acrescimo = money(request.form.get("acrescimo"))
        total = pecas + mao - desconto + acrescimo
        parcelas = max(1, int(request.form.get("parcelas") or 1))
        valor_parcela = round(total / parcelas, 2)
        params = {
            "cliente_id": request.form["cliente_id"], "veiculo_id": request.form["veiculo_id"],
            "data": request.form.get("data") or datetime.now().strftime("%Y-%m-%d"),
            "status": normalizar(request.form.get("status","ABERTO")),
            "descricao": normalizar(request.form.get("descricao","")),
            "pecas_desc": normalizar(request.form.get("pecas_desc","")),
            "pecas_valor": pecas, "mao_obra_desc": normalizar(request.form.get("mao_obra_desc","")),
            "mao_obra_valor": mao, "desconto": desconto, "acrescimo": acrescimo, "total": total,
            "pagamento": normalizar(request.form.get("pagamento","NÃO INFORMADO")),
            "parcelas": parcelas, "valor_parcela": valor_parcela,
            "primeira_parcela": request.form.get("primeira_parcela") or datetime.now().strftime("%Y-%m-%d"),
            "observacoes": normalizar(request.form.get("observacoes","")),
        }
        if request.form.get("edit_id"):
            params["id"] = int(request.form["edit_id"])
            execute("""UPDATE orcamentos SET cliente_id=:cliente_id, veiculo_id=:veiculo_id, data=:data, status=:status,
                       descricao=:descricao, pecas_desc=:pecas_desc, pecas_valor=:pecas_valor,
                       mao_obra_desc=:mao_obra_desc, mao_obra_valor=:mao_obra_valor,
                       desconto=:desconto, acrescimo=:acrescimo, total=:total, pagamento=:pagamento,
                       parcelas=:parcelas, valor_parcela=:valor_parcela, primeira_parcela=:primeira_parcela,
                       observacoes=:observacoes WHERE id=:id""", params)
            oid = params["id"]
        else:
            with engine.begin() as con:
                result = con.execute(text("""INSERT INTO orcamentos(cliente_id,veiculo_id,data,status,descricao,pecas_desc,pecas_valor,
                    mao_obra_desc,mao_obra_valor,desconto,acrescimo,total,pagamento,parcelas,valor_parcela,primeira_parcela,observacoes)
                    VALUES(:cliente_id,:veiculo_id,:data,:status,:descricao,:pecas_desc,:pecas_valor,:mao_obra_desc,:mao_obra_valor,
                    :desconto,:acrescimo,:total,:pagamento,:parcelas,:valor_parcela,:primeira_parcela,:observacoes) RETURNING id"""), params)
                oid = result.scalar()
        recalcular_parcelas(oid)
        return redirect(url_for("orcamentos"))

    clientes = fetchall("SELECT * FROM clientes ORDER BY nome")
    veiculos = fetchall("""SELECT v.*, c.nome cliente FROM veiculos v
                           LEFT JOIN clientes c ON c.id=v.cliente_id ORDER BY c.nome, v.modelo""")
    lista = fetchall("""SELECT o.*, c.nome cliente, c.telefone telefone, v.modelo carro, v.placa placa
                        FROM orcamentos o
                        LEFT JOIN clientes c ON c.id=o.cliente_id
                        LEFT JOIN veiculos v ON v.id=o.veiculo_id
                        ORDER BY o.id DESC""")
    edit = fetchone("SELECT * FROM orcamentos WHERE id=:id", {"id": edit_id}) if edit_id else None
    return render_template("orcamentos.html", clientes=clientes, veiculos=veiculos, orcamentos=lista, edit=edit)

@app.route("/orcamentos/excluir/<int:id>")
@login_required
def excluir_orcamento(id):
    execute("DELETE FROM financeiro WHERE orcamento_id=:id", {"id": id})
    execute("DELETE FROM orcamentos WHERE id=:id", {"id": id})
    return redirect(url_for("orcamentos"))

def get_orcamento(id):
    return fetchone("""SELECT o.*, c.nome cliente, c.telefone telefone, c.endereco endereco,
                      v.modelo carro, v.placa placa, v.ano ano, v.cor cor
                      FROM orcamentos o
                      LEFT JOIN clientes c ON c.id=o.cliente_id
                      LEFT JOIN veiculos v ON v.id=o.veiculo_id
                      WHERE o.id=:id""", {"id": id})

@app.route("/orcamentos/pdf/<int:id>")
@login_required
def pdf_orcamento(id):
    o = get_orcamento(id)
    if not o:
        return "ORÇAMENTO NÃO ENCONTRADO", 404
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    w,h = A4
    c.setFillColor(colors.HexColor("#252B30"))
    c.rect(0, h-4.2*cm, w, 4.2*cm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(2*cm, h-1.5*cm, "AUTO MECÂNICA ADEMAR")
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, h-2.2*cm, "MECÂNICA EM GERAL")
    c.setFont("Helvetica", 9)
    c.drawString(2*cm, h-2.8*cm, "RUA CONCEIÇÃO DA BARRA, 436 - SÃO SALVADOR")
    c.drawString(2*cm, h-3.3*cm, "FIXO: 3477-7455 | WHATSAPP: (31) 98801-7455")
    c.setFillColor(colors.HexColor("#A94343"))
    c.roundRect(w-5.2*cm, h-2.8*cm, 3.8*cm, 1.1*cm, 8, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 13)
    c.drawCentredString(w-3.3*cm, h-2.4*cm, f"ORÇAMENTO #{id}")

    y = h-5.1*cm
    def section(title):
        nonlocal y
        c.setFillColor(colors.HexColor("#F0E8E8"))
        c.roundRect(1.6*cm, y-0.2*cm, w-3.2*cm, 0.75*cm, 6, fill=1, stroke=0)
        c.setFillColor(colors.HexColor("#333333"))
        c.setFont("Helvetica-Bold", 11)
        c.drawString(2*cm, y, title)
        y -= 0.85*cm

    section("CLIENTE E VEÍCULO")
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#333333"))
    for line in [
        f"CLIENTE: {o['cliente']}",
        f"TELEFONE: {o['telefone']}",
        f"VEÍCULO: {o['carro']} | PLACA: {o['placa']} | ANO: {o['ano']} | COR: {o['cor']}",
        f"DATA: {o['data']} | STATUS: {o['status']}",
    ]:
        c.drawString(2*cm, y, line[:115])
        y -= 0.48*cm
    y -= 0.2*cm

    section("PEÇAS E MÃO DE OBRA")
    rows = [("PEÇAS", o["pecas_desc"], o["pecas_valor"]), ("MÃO DE OBRA", o["mao_obra_desc"], o["mao_obra_valor"])]
    for titulo, desc, valor in rows:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(2*cm, y, titulo)
        c.drawRightString(w-2*cm, y, brl(valor))
        y -= 0.45*cm
        c.setFont("Helvetica", 9)
        for line in (desc or "-").split("\n"):
            c.drawString(2.2*cm, y, line[:100])
            y -= 0.35*cm
        y -= 0.25*cm

    section("PAGAMENTO E TOTAL")
    c.setFont("Helvetica", 10)
    for line in [
        f"DESCONTO: {brl(o['desconto'])}",
        f"ACRÉSCIMO: {brl(o['acrescimo'])}",
        f"PAGAMENTO: {o['pagamento']} | PARCELAS: {o['parcelas']}x DE {brl(o['valor_parcela'])}",
        f"PRIMEIRA PARCELA: {o['primeira_parcela']}",
    ]:
        c.drawString(2*cm, y, line)
        y -= 0.45*cm
    c.setFillColor(colors.HexColor("#A94343"))
    c.setFont("Helvetica-Bold", 17)
    c.drawRightString(w-2*cm, y, f"TOTAL: {brl(o['total'])}")
    y -= 0.9*cm

    c.setFillColor(colors.HexColor("#333333"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(2*cm, y, "OBSERVAÇÕES")
    y -= 0.4*cm
    c.setFont("Helvetica", 9)
    c.drawString(2*cm, y, (o["observacoes"] or "-")[:105])

    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#777777"))
    c.drawCentredString(w/2, 1.2*cm, "AUTO MECÂNICA ADEMAR • MECÂNICA EM GERAL • OBRIGADO PELA CONFIANÇA")
    c.save()
    buffer.seek(0)
    return send_file(buffer, as_attachment=False, download_name=f"ORCAMENTO_{id}.pdf", mimetype="application/pdf")

@app.route("/orcamentos/whatsapp/<int:id>")
@login_required
def whatsapp(id):
    o = get_orcamento(id)
    if not o:
        return redirect(url_for("orcamentos"))
    numero = "".join(ch for ch in (o["telefone"] or "") if ch.isdigit())
    msg = f"""Olá, {o['cliente']}! 👋

Aqui é da Auto Mecânica Ademar 🔧🚗

Segue o orçamento do seu veículo {o['carro']} - placa {o['placa']}.

💰 Total: {brl(o['total'])}
💳 Pagamento: {o['pagamento']} - {o['parcelas']}x de {brl(o['valor_parcela'])}

Qualquer dúvida estou à disposição.
Agradecemos a confiança! 🤝"""
    return redirect("https://wa.me/55" + numero + "?text=" + urllib.parse.quote(msg))

@app.route("/financeiro", methods=["GET","POST"])
@login_required
def financeiro():
    if request.method == "POST":
        execute("""INSERT INTO financeiro(data,tipo,descricao,valor,forma,status)
                   VALUES(:data,:tipo,:descricao,:valor,:forma,:status)""",
                {"data": request.form["data"], "tipo": normalizar(request.form["tipo"]),
                 "descricao": normalizar(request.form["descricao"]), "valor": money(request.form["valor"]),
                 "forma": normalizar(request.form["forma"]), "status": normalizar(request.form["status"])})
        return redirect(url_for("financeiro"))
    itens = fetchall("SELECT * FROM financeiro ORDER BY data DESC, id DESC LIMIT 300")
    return render_template("financeiro.html", itens=itens)

@app.route("/financeiro/pago/<int:id>")
@login_required
def financeiro_pago(id):
    execute("UPDATE financeiro SET status='PAGO' WHERE id=:id", {"id": id})
    return redirect(url_for("financeiro"))

@app.route("/financeiro/excluir/<int:id>")
@login_required
def excluir_financeiro(id):
    execute("DELETE FROM financeiro WHERE id=:id", {"id": id})
    return redirect(url_for("financeiro"))

@app.route("/relatorios")
@login_required
def relatorios():
    ano = request.args.get("ano") or datetime.now().strftime("%Y")
    mes = request.args.get("mes") or datetime.now().strftime("%m")
    ym = f"{ano}-{mes}"
    mensal = fetchall("""SELECT forma, status, COUNT(*) qtd, COALESCE(SUM(valor),0) total
                         FROM financeiro WHERE substr(data,1,7)=:ym AND tipo='ENTRADA'
                         GROUP BY forma,status ORDER BY forma,status""", {"ym": ym})
    saidas = fetchone("""SELECT COALESCE(SUM(valor),0) total FROM financeiro
                         WHERE substr(data,1,7)=:ym AND tipo='SAÍDA'""", {"ym": ym})["total"]
    entradas = fetchone("""SELECT COALESCE(SUM(valor),0) total FROM financeiro
                           WHERE substr(data,1,7)=:ym AND tipo='ENTRADA' AND status='PAGO'""", {"ym": ym})["total"]
    anual = fetchall("""SELECT substr(data,1,7) mes,
                        COALESCE(SUM(CASE WHEN tipo='ENTRADA' THEN valor ELSE -valor END),0) saldo
                        FROM financeiro WHERE substr(data,1,4)=:ano
                        GROUP BY substr(data,1,7) ORDER BY mes""", {"ano": ano})
    parcelas = fetchall("""SELECT * FROM financeiro WHERE tipo='ENTRADA' AND status='PENDENTE'
                           ORDER BY data ASC LIMIT 100""")
    return render_template("relatorios.html", mensal=mensal, anual=anual, parcelas=parcelas,
                           entradas=entradas, saidas=saidas, lucro=entradas-saidas, ano=ano, mes=mes)

if __name__ == "__main__":
    app.run(debug=True)
